spring:
  config:
    import: optional:file:/opt/irm/etc/fhirext-statistics.env[.properties]
#    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
  jackson:
    deserialization:
      fail-on-unknown-properties: true
logging:
  level:
    root: error
    org.springframework: error
    org.hibernate: error
    kr.irm.FHIRext.statistics: info
server:
  port: 3001

management:
  endpoints:
    web:
      exposure:
        include: "health"